name: Nix CI

on: pull_request

concurrency:
  group: "${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check
        run: |
          nix flake check --print-build-logs -j auto
